"""06.03.24 change diss

Revision ID: b6ec68fb7cba
Revises: ebcb7e9d555a
Create Date: 2024-03-06 14:05:58.521257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ec68fb7cba'
down_revision: Union[str, None] = 'ebcb7e9d555a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dissertation', sa.Column('dissertation_date', sa.Date(), nullable=True))
    op.drop_column('dissertation', 'created_date')
    op.drop_column('dissertation', 'number_of_prototypes')
    op.add_column('rid', sa.Column('rid_date', sa.Date(), nullable=True))
    op.drop_column('rid', 'created_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rid', sa.Column('created_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('rid', 'rid_date')
    op.add_column('dissertation', sa.Column('number_of_prototypes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dissertation', sa.Column('created_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('dissertation', 'dissertation_date')
    # ### end Alembic commands ###
